feelathome/feelathome/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

feelathome/polls/urls.py
#################################################################################
# Copyright (C) 2022 Kostiantyn Klochko <kostya_klochko@ukr.net>                #
#                                                                               #
# This file is part of feel-at-home.                                            #
#                                                                               #
# feel-at-home is free software: you can redistribute it and/or modify it under #
# the terms of the GNU Affero General Public License as published by the Free   #
# Software Foundation, either version 3 of the License, or (at your option)     #
# any later version.                                                            #
#                                                                               #
# feel-at-home is distributed in the hope that it will be useful, but WITHOUT   #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS #
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more  #
# details.                                                                      #
#                                                                               #
# You should have received a copy of the GNU Affero General Public License      #
# along with feel-at-home. If not, see <https://www.gnu.org/licenses/>.         #
#################################################################################
from django.conf.urls import include
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('good/<int:good_id>/', views.detail, name='detail'),
    path('', include('django.contrib.auth.urls')),
    path('sign-up', views.sign_up, name='sign_up'),
    path('cabinet', views.cabinet, name='cabinet'),
    path('orders', views.orders, name='orders'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('cart', views.cart, name='cart'),
    path('cart/confirm', views.cart_confirm, name='cart_confirm'),
    path('cart/<int:container_id>/', views.cart_item, name='cart_item'),
]

feelathome/polls/forms.py
#################################################################################
# Copyright (C) 2022 Kostiantyn Klochko <kostya_klochko@ukr.net>                #
#                                                                               #
# This file is part of feel-at-home.                                            #
#                                                                               #
# feel-at-home is free software: you can redistribute it and/or modify it under #
# the terms of the GNU Affero General Public License as published by the Free   #
# Software Foundation, either version 3 of the License, or (at your option)     #
# any later version.                                                            #
#                                                                               #
# feel-at-home is distributed in the hope that it will be useful, but WITHOUT   #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS #
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more  #
# details.                                                                      #
#                                                                               #
# You should have received a copy of the GNU Affero General Public License      #
# along with feel-at-home. If not, see <https://www.gnu.org/licenses/>.         #
#################################################################################
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class GoodBuyForm(forms.Form):
    def __init__(self, *args, **kwargs):
        validators = []
        min_value = kwargs.pop("min_value", None)
        max_value = kwargs.pop("max_value", None)
        count = kwargs.pop("count", None)
        form_type = kwargs.pop("form_type", None)
        if not min_value is None:
            validators.append(MinValueValidator(min_value))
        if not max_value is None:
            validators.append(MaxValueValidator(max_value))
        if count is None:
            count = 1
        super().__init__(*args, **kwargs)
        self.fields['count'] = forms.IntegerField(
            initial=count,
            validators=validators,
        )
        self.helper = FormHelper()
        # if a good page
        if form_type is None:
            self.helper.add_input(Submit('submit', 'Buy', css_class='btn-success'))
        # if a cart item page
        elif form_type is "change":
            self.helper.add_input(Submit('submit', 'Change', css_class='btn-success'))
            self.helper.add_input(Submit('cancel', 'Cancel', css_class='btn-danger', formnovalidate='formnovalidate'))
        self.helper.form_method = 'POST'

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length = 32)
    last_name = forms.CharField(max_length = 32)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

    def clean(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email exists")
        return self.cleaned_data
#----------------------------- CartConfirmForm ----------------------------
stripeValidator = RegexValidator(r'[0-9]{4} [0-9]{4} [0-9]{4} [0-9]{4}',
                                 'Only digits with separation allowed. Example: dddd dddd dddd dddd.')
mmyy = RegexValidator(r'[0-2][0-9][/][0-9]{2}', 'Use only format mm/yy. Example: 06/23.')
numberValidator = RegexValidator(r'[0-9]{3}', 'Only digits allowed.')

class CartConfirmForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn-success'))
        self.helper.add_input(Submit('cancel', 'Cancel', css_class='btn-danger', formnovalidate='formnovalidate'))
        self.helper.form_method = 'POST'

        self.fields['destination'] = forms.CharField(max_length=256)
        self.fields['card'] = forms.CharField(min_length=19, max_length=19, validators=[stripeValidator])
        self.fields['mm_yy'] = forms.CharField(min_length=5, max_length=5, validators=[mmyy])
        self.fields['cvv'] = forms.CharField(min_length=3, max_length=3, validators=[numberValidator])

feelathome/polls/views.py
#################################################################################
# Copyright (C) 2022 Kostiantyn Klochko <kostya_klochko@ukr.net>                #
#                                                                               #
# This file is part of feel-at-home.                                            #
#                                                                               #
# feel-at-home is free software: you can redistribute it and/or modify it under #
# the terms of the GNU Affero General Public License as published by the Free   #
# Software Foundation, either version 3 of the License, or (at your option)     #
# any later version.                                                            #
#                                                                               #
# feel-at-home is distributed in the hope that it will be useful, but WITHOUT   #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS #
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more  #
# details.                                                                      #
#                                                                               #
# You should have received a copy of the GNU Affero General Public License      #
# along with feel-at-home. If not, see <https://www.gnu.org/licenses/>.         #
#################################################################################
from django.db.models.query import QuerySet
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.core.exceptions import PermissionDenied

from .decorators import forbidden_cart_item, forbidden_order
from .forms import CartConfirmForm, GoodBuyForm, RegisterForm

from .models import Good, Order, Container, ContainersAndOrder
from .filters import GoodFilter, OrderFilter, ContainerFilter

from datetime import datetime
############################### Goods ################################

def index(request):
    goods_list = Good.objects.all()
    goods_filter = GoodFilter(request.GET, queryset=goods_list)
    context = {'goods_filter': goods_filter}
    if request.method == "POST":
        good_id = request.POST.get("good-id")
        if not request.user.is_authenticated:
            return redirect('polls:login')
        add_to_cart(request, good_id)

    return render(request, 'polls/index.html', context)

def detail(request, good_id):
    good = get_object_or_404(Good, pk=good_id)
    buy_form = GoodBuyForm(request.POST or None, min_value=1, max_value=good.count)
    context = {'good': good, 'buy_form': buy_form}
    if request.method == "POST":
        if buy_form.is_valid():
            count = buy_form.cleaned_data.get("count")
            if count != None:
                if not request.user.is_authenticated:
                    return redirect('polls:login')
                add_to_cart(request, good_id, count)
            
    return render(request, 'polls/detail_good.html', context)

############################### Orders ###############################

@login_required(login_url='polls:login')
def orders(request):
    user_id = request.user.id
    user_groups = list(map(lambda g: g.name,request.user.groups.all()))

    if 'admin' in user_groups:
        order_list = Order.objects.all()
    elif 'courier' in user_groups:
        order_list = Order.objects.filter(status__in=["DOING","DONE","CANCELED"]).all()
    elif 'shop assistant' in user_groups:
        order_list = Order.objects.filter(status__in=["TODO","DOING","DONE","CANCELED"]).all()
    else:
        order_list = Order.objects.filter(receiver_id=user_id, status__in=["TODO","DOING","CONFIRM","DONE","CANCELED"]).all()

    orders_filter = OrderFilter(request.GET, queryset=order_list)
    context = {'orders_filter': orders_filter}
    return render(request, 'polls/orders.html', context)

@login_required(login_url='polls:login')
@forbidden_order
def order_detail(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    user_groups = list(map(lambda g: g.name,request.user.groups.all()))
    containers_ids = ContainersAndOrder.objects.select_related().filter(orderId_id = order_id).values('containerId_id')
    containers = Container.objects.filter(id__in=containers_ids)
    containers_filter = ContainerFilter(request.GET, queryset=containers)
    context = {'order': order, 'containers_filter': containers_filter, 'user_groups': user_groups}
    if request.method == "POST":
        if "TODO" in request.POST:
            print("TODO")
            order.status = "DOING"
        elif "DONE" in request.POST:
            print("DONE")
            order.status = "CONFIRM"
        elif "CONFIRM" in request.POST:
            print("CONFIRM")
            order.status = "DONE"
        order.save()
    return render(request, 'polls/order.html', context)

############################### Cart ###############################
@login_required(login_url='polls:login')
def cart(request):
    user_id = request.user.id
    cart, created = get_cart(request)


    containers_ids = ContainersAndOrder.objects.select_related().filter(orderId_id = cart.id).values('containerId_id')
    containers = Container.objects.filter(id__in=containers_ids)
    containers_filter = ContainerFilter(request.GET, queryset=containers)
    context = {'cart': cart, 'containers_filter': containers_filter}
    if request.method == "POST":
        delete_container_id = request.POST.get("delete-container-id")
        if not delete_container_id is None:
            print(f"{delete_container_id=}")
            container = get_object_or_404(Container, pk=delete_container_id)
            good = get_object_or_404(Good, pk=container.goodId.id)
            good.count += container.count
            good.save()
            obj = Container.objects.filter(id=delete_container_id).delete()
    if is_cart_empty(request):
        context["empty_cart"] = True
    return render(request, 'polls/cart_items.html', context)

@login_required(login_url='polls:login')
@forbidden_cart_item
def cart_item(request, container_id):
    user_id = request.user.id
    cart, created = get_cart(request)

    container = get_object_or_404(Container, pk=container_id)
    good = get_object_or_404(Good, pk=container.goodId.id)
    max_count = good.count + container.count
    context = {'container': container}
    if request.method == "POST":
        if "cancel" in request.POST:
            return redirect('polls:cart')
        container_form = GoodBuyForm(request.POST or None, min_value=1, max_value=max_count, form_type="change")

        if container_form.is_valid():
            count = container_form.cleaned_data["count"]
            if count != None:
                good.count = good.count + container.count - count
                container.count = count
                container.save()
                good.save()
                return redirect('polls:cart')
        else:
            context['container_form'] = container_form
    else:
        container_form = GoodBuyForm(count=container.count, min_value=1, max_value=max_count, form_type="change")
        context['container_form'] = container_form
    return render(request, 'polls/cart_item.html', context)

def add_to_cart(request, good_id, count = 1):
    good = Good.objects.filter(id=good_id).first()
    if good is None:
        return

    cart, created = get_cart(request)

    containers_ids = ContainersAndOrder.objects.select_related().filter(orderId_id = cart).values('containerId_id')
    containers = Container.objects.filter(id__in=containers_ids)

    container, created = containers.get_or_create(
        name = good.name,
        goodId_id = good.id,
        defaults = {
            'discount': 0,
            'price': 0,
            'count': 1,
        },
    )

    if created:
        # Create relation between a container and an order if the container is new.
        containerAndOrder, created = ContainersAndOrder.objects.get_or_create(
            orderId = cart,
            containerId = container,
        )
        # add price to the container
        container.price = good.price
        container.count = count
        # Save model changes in DB.
        container.save()
    else:
        container.count += count
        # Save model changes in DB.
        container.save()
    good.count -= count
    good.save()

def get_cart(request):
    """
    Create the cart if not exists.
    Return cart, created
    """
    user_id = request.user.id
    cart, created = Order.objects.get_or_create(
        receiver_id = user_id,
        status = "CART",
        defaults = {
            'order_date': datetime.now(),
            'price': 0,
            'destination': '',
        },
    )
    return cart, created

def get_cart_price(request):
    """
    Return cart price.
    """
    user_id = request.user.id
    cart, created = get_cart(request)

    containers_ids = ContainersAndOrder.objects.select_related().filter(orderId_id = cart.id).values('containerId_id')
    containers = Container.objects.filter(id__in=containers_ids)
    price = 0
    for container in containers:
        price += container.price * (1 - container.discount)
    return price

def is_cart_empty(request) -> bool:
    """
    Return True if no items in the cart.
    """
    user_id = request.user.id
    cart, created = get_cart(request)

    containers_ids = ContainersAndOrder.objects.select_related().filter(orderId_id = cart.id).values('containerId_id')
    containers = Container.objects.filter(id__in=containers_ids)
    if len(containers) == 0:
        return True
    return False

@login_required(login_url='polls:login')
def cart_confirm(request):
    user_id = request.user.id
    cart, created = get_cart(request)

feelathome/templates/polls/cart_item.html
<!--
#################################################################################
# Copyright (C) 2022 Kostiantyn Klochko <kostya_klochko@ukr.net>                #
#                                                                               #
# This file is part of feel-at-home.                                            #
#                                                                               #
# feel-at-home is free software: you can redistribute it and/or modify it under #
# the terms of the GNU Affero General Public License as published by the Free   #
# Software Foundation, either version 3 of the License, or (at your option)     #
# any later version.                                                            #
#                                                                               #
# feel-at-home is distributed in the hope that it will be useful, but WITHOUT   #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS #
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more  #
# details.                                                                      #
#                                                                               #
# You should have received a copy of the GNU Affero General Public License      #
# along with feel-at-home. If not, see <https://www.gnu.org/licenses/>.         #
#################################################################################
-->
{% extends 'base.html' %}
{% if container %}
  {% block title %}container.name{% endblock %}
{% endif %}
{% load static %}
{% load crispy_forms_tags %}
{% block extends_styles %}
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  {% if container %}
  <center><h1>Item information</h1></center>
  <dl class="row">
    <dt class="col-sm-3">Name:</dt>
    <dd class="col-sm-9"><a href="{% url 'polls:detail' container.goodId.id %}">{{ container.name }}</a></dd>

    <dt class="col-sm-3">Price:</dt>
    <dd class="col-sm-9">{{ container.price }}$</dd>
  </dl>
  <form method="POST">
    {% csrf_token %}
    {% crispy container_form %}
  </form>
  {% else %}
    <center><h1>Something went wrong.</h1></center>
    <p>No item yet.</p>
  {% endif %}

{% else %}
  <h1>You are not authorized!!! Please, sign in or sign up.</h1>
{% endif %}
{% endblock %}

feelathome/templates/polls/cart_items.html
<!--
#################################################################################
# Copyright (C) 2022 Kostiantyn Klochko <kostya_klochko@ukr.net>                #
#                                                                               #
# This file is part of feel-at-home.                                            #
#                                                                               #
# feel-at-home is free software: you can redistribute it and/or modify it under #
# the terms of the GNU Affero General Public License as published by the Free   #
# Software Foundation, either version 3 of the License, or (at your option)     #
# any later version.                                                            #
#                                                                               #
# feel-at-home is distributed in the hope that it will be useful, but WITHOUT   #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS #
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more  #
# details.                                                                      #
#                                                                               #
# You should have received a copy of the GNU Affero General Public License      #
# along with feel-at-home. If not, see <https://www.gnu.org/licenses/>.         #
#################################################################################
-->
{% extends 'base.html' %}
{% block title %}Cart{% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block extends_styles %}
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  {% if cart %}
  <center><h1>Cart information</h1></center>
  {% else %}
  <h1>Something went wrong.</h1>
  {% endif %}

  {% if containers_filter %}
  <center><h2>Items in the cart</h2></center>
  <form method="get" class="form-bottom-margin">
    {{ containers_filter.form|crispy }}
    <button class="btn btn-sm btn-danger" type="submit">Sort</button>
  </form>
  <table class="table table-striped">
    <tr>
      <td>Name</td>
      <td>Price</td>
      <td>Count</td>
      <td></td>
      <td></td>
    </tr>
    {% for container in containers_filter.qs %}
      <tr>
        <td><a href="{% url 'polls:detail' container.goodId_id %}">{{ container.name }}</a></td>
        <td>{{ container.price }}</td>
        <td>{{ container.count }}</td>
	<td>
          <button class="btn btn-success" onclick="window.location.href='{% url 'polls:cart_item' container.id %}';">Change</button>
	</td>
	<td>
	  <form method="POST">
	    {% csrf_token %}
	    <button type="submit" class="btn btn-danger" name="delete-container-id" value="{{container.id}}">Remove</button>
	  </form>
	</td>
      </tr>
    {% endfor %}
  </table>
  {% if not empty_cart %}
    <button class="btn btn-danger form-bottom-margin" onclick="window.location.href='{% url 'polls:cart_confirm' %}'">Confirm</button>
  {% endif %}
  {% else %}
      <p>No items yet.</p>
  {% endif %}

{% else %}
  <h1>You are not authorized!!! Please, sign in or sign up.</h1>
{% endif %}
{% endblock %}

feelathome/templates/polls/index.html
<!--
#################################################################################
# Copyright (C) 2022 Kostiantyn Klochko <kostya_klochko@ukr.net>                #
#                                                                               #
# This file is part of feel-at-home.                                            #
#                                                                               #
# feel-at-home is free software: you can redistribute it and/or modify it under #
# the terms of the GNU Affero General Public License as published by the Free   #
# Software Foundation, either version 3 of the License, or (at your option)     #
# any later version.                                                            #
#                                                                               #
# feel-at-home is distributed in the hope that it will be useful, but WITHOUT   #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS #
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more  #
# details.                                                                      #
#                                                                               #
# You should have received a copy of the GNU Affero General Public License      #
# along with feel-at-home. If not, see <https://www.gnu.org/licenses/>.         #
#################################################################################
-->
{% extends 'base.html' %}
{% block title %}Goods{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block extends_styles %}
{% endblock %}

{% block content %}
  <center><h1>Catalog of goods</h1></center>
  {% if goods_filter %}
    <form method="get" class="form-bottom-margin">
      {{ goods_filter.form|crispy }}
      <button class="btn btn-sm btn-danger" type="submit">Sort</button>
    </form>
    <table class="table table-striped">
      <tr>
        <td>Good name</td>
        <td>Price</td>
        <td>Availability</td>
	<td></td>
      </tr>
      {% for good in goods_filter.qs %}
      <tr>
        <td><a href="{% url 'polls:detail' good.id %}">{{ good.name }}</a></td>
        <td>{{ good.price }}$</td>
        {% if good.is_empty %}
        <td>Available</td>
        <td>
	  <form method="POST">
	    {% csrf_token %}
	    <button type="submit" class="btn btn-success" name="good-id" value="{{good.id}}">Buy</button>
	  </form>
	</td>
        {% else %}
        <td>Run Out</td>
	<td></td>
        {% endif %}
      </tr>
      {% endfor %}
    </table>
  {% else %}
      <p>No goods are available yet.</p>
  {% endif %}
{% endblock %}

feelathome/templates/polls/order.html
<!--
#################################################################################
# Copyright (C) 2022 Kostiantyn Klochko <kostya_klochko@ukr.net>                #
#                                                                               #
# This file is part of feel-at-home.                                            #
#                                                                               #
# feel-at-home is free software: you can redistribute it and/or modify it under #
# the terms of the GNU Affero General Public License as published by the Free   #
# Software Foundation, either version 3 of the License, or (at your option)     #
# any later version.                                                            #
#                                                                               #
# feel-at-home is distributed in the hope that it will be useful, but WITHOUT   #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS #
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more  #
# details.                                                                      #
#                                                                               #
# You should have received a copy of the GNU Affero General Public License      #
# along with feel-at-home. If not, see <https://www.gnu.org/licenses/>.         #
#################################################################################
-->
{% extends 'base.html' %}
{% block title %}Order{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block extends_styles %}
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  {% if order %}
  <center><h1>Order information</h1></center>
  <dl class="row">
    <dt class="col-sm-3">Oder id:</dt>
    <dd class="col-sm-9">{{ order.id }}.</dd>

    <dt class="col-sm-3">Price:</dt>
    <dd class="col-sm-9">{{ order.price }}$</dd>

    <dt class="col-sm-3">Destination:</dt>
    <dd class="col-sm-9">{{ order.destination }}.</dd>

    <dt class="col-sm-3">Status:</dt>
    <dd class="col-sm-9">{{ order.status|lower|capfirst }}</dd>
    </dd>
  </dl>
  {% else %}
  <h1>Something went wrong.</h1>
  {% endif %}

  {% if containers_filter %}
  <center><h1>Items in the order</h1></center>
  <form method="get" class="form-bottom-margin">
    {{ containers_filter.form|crispy }}
    <button class="btn btn-sm btn-danger" type="submit">Sort</button>
  </form>
  <table class="table table-striped">
    <tr>
      <td>Name</td>
      <td>Price</td>
      <td>Count</td>
    </tr>
    {% for container in containers_filter.qs %}
    <tr>
      <td><a href="{% url 'polls:detail' container.goodId_id %}">{{ container.name }}</a></td>
      <td>{{ container.price }}</td>
      <td>{{ container.count }}</td>
    </tr>
    {% endfor %}
  </table>
  {% if order %}
    {% if 'shop assistant' in user_groups and order.status == "TODO" %}
	<form method="POST" class="btn btn-danger form-bottom-margin">
	  {% csrf_token %}
	  <button type="submit" class="btn btn-danger" name="TODO" value="TODO">Preparing is done</button>
	</form>
    {% endif %}
    {% if 'courier' in user_groups and order.status == "DOING" %}
	<form method="POST" class="btn btn-danger form-bottom-margin">
	  {% csrf_token %}
	  <button type="submit" class="btn btn-danger" name="DONE" value="DONE">Delivered</button>
	</form>
    {% endif %}
    {% if 'customer' in user_groups and order.status == "CONFIRM" and order.receiver == user %}
	<form method="POST" class="btn btn-danger form-bottom-margin">
	  {% csrf_token %}
	  <button type="submit" class="btn btn-danger" name="CONFIRM" value="CONFIRM">Confirm</button>
	</form>
    {% endif %}
  {% endif %}
  {% else %}
      <p>No items yet.</p>
  {% endif %}

{% else %}
  <h1>You are not authorized!!! Please, sign in or sign up.</h1>
{% endif %}
{% endblock %}

feelathome/templates/polls/orders.html
<!--
#################################################################################
# Copyright (C) 2022 Kostiantyn Klochko <kostya_klochko@ukr.net>                #
#                                                                               #
# This file is part of feel-at-home.                                            #
#                                                                               #
# feel-at-home is free software: you can redistribute it and/or modify it under #
# the terms of the GNU Affero General Public License as published by the Free   #
# Software Foundation, either version 3 of the License, or (at your option)     #
# any later version.                                                            #
#                                                                               #
# feel-at-home is distributed in the hope that it will be useful, but WITHOUT   #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS #
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more  #
# details.                                                                      #
#                                                                               #
# You should have received a copy of the GNU Affero General Public License      #
# along with feel-at-home. If not, see <https://www.gnu.org/licenses/>.         #
#################################################################################
-->
{% extends 'base.html' %}
{% block title %}Orders{% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block extends_styles %}
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
  <center><h1>Yours orders</h1></center>
  {% if orders_filter %}
  <form method="get" class="form-bottom-margin">
    {{ orders_filter.form|crispy }}
    <button class="btn btn-sm btn-danger" type="submit">Sort</button>
  </form>
  <table class="table table-striped">
    <tr>
      <td>ID</td>
      <td>Date</td>
      <td>Price</td>
      <td>Destination</td>
      <td>Status</td>
    </tr>
    {% for order in orders_filter.qs %}
    <tr>
      <td><a href="{% url 'polls:order_detail' order.id %}">{{ order.id }}</a></td>
      <td>{{ order.order_date }}</td>
      <td>{{ order.price }}$</td>
      <td>{{ order.destination }}</td>
      <td> {{ order.status|lower|capfirst }}</td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
      <p>No orders yet.</p>
  {% endif %}

{% else %}
  <h1>You are not authorized!!! Please, sign in or sign up.</h1>
{% endif %}
{% endblock %}